<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>io.datacraft</groupId><artifactId>datacraft</artifactId><version>0.1.0-SNAPSHOT</version></parent>
    <artifactId>datacraft-server</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>datacraft-common</module>
        <module>datacraft-api</module>
        <module>datacraft-auth</module>
        <module>datacraft-datasource</module>
        <module>datacraft-metadata</module>
        <module>datacraft-pipeline</module>
        <module>datacraft-execution</module>
        <module>datacraft-quality</module>
        <module>datacraft-bootstrap</module>
    </modules>
</project>
